name: Validate links

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  contents: read

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link checker report
          content-filepath: ./lychee/out.md
          labels: report, automated-issue

      - name: Assign issue
        if: env.lychee_exit_code != 0
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignees = ["gustavofreze"];
            const issueNumber = context.payload.issue.number;
            const octokit = context.octokit;
            await octokit.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              assignees: assignees,
            });
