name: Validate links

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  contents: read

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link checker report
          content-filepath: ./lychee/out.md
          labels: report, automated-issue

      - name: Assign issue
        if: env.lychee_exit_code != 0
        run: |
          assignees="gustavofreze"
          issue_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"assignees\":[\"$assignees\"]}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$issue_number/assignees"
