name: Validate links

on:
  issues:
    types: [ opened ]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link checker report
          content-filepath: ./lychee/out.md
          labels: report, automated-issue

      - name: Assign issue
        if: env.lychee_exit_code != 0
        uses: pozil/auto-assign-issue@v1.11.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: gustavofreze
          numOfAssignee: 1
