name: Validate links

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write
  contents: read

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Create issue
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link checker report
          content-filepath: ./lychee/out.md
          labels: report, automated-issue

      - name: Assign issue
        if: env.lychee_exit_code != 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.squirrel-girl-preview+json" \
            -d '{
              "assignees": ["your-username"]
            }' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees"
